my-runners-keeper/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/login' => 'sessions#login'

  post 'sessions/logout' => 'sessions#logout'

  root 'pages#index'

  get 'runners/:id' => 'runners#show', as: 'runner'

  get 'runners' => 'runners#index'

  get 'runners/new' => 'runners#new'

  post 'runners/create' => 'runners#create'

end

my-runners-keeper/app/models/run.rb
class Run < ActiveRecord::Base
  belongs_to :runner
  validates :distance, presence: true

end

my-runners-keeper/app/models/runner.rb
class Runner < ActiveRecord::Base
  has_many :runs
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, length: { minimum: 10 }
  validates :email, format: { with: /@/, message: "Sorry, that is not a proper email address." }

  has_secure_password

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

my-runners-keeper/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_runner
    @current_runner ||= Runner.find_by(id: session[:runner_id]) if session[:runner_id]
  end

  def logged_in?
    session[:runner_id].present?
  end

  helper_method :current_runner
  helper_method :logged_in?

end

my-runners-keeper/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end



end

my-runners-keeper/app/controllers/runners_controller.rb
class RunnersController < ApplicationController

  def new
    @runner = Runner.new
  end

  def create
    @runner = Runner.new(runner_params)
    if @runner.save
      redirect_to "/"
    else
      render "new"
    end
  end


  def show
    @runner = Runner.find_by(id: params[:id])
    @runs = @runner.runs
  end

  def index
    @runners = Runner.all
  end

  private

  def runner_params
    params.require(:runner).permit(:first_name, :last_name, :captain, :email, :img_url, :password)
  end


end

my-runners-keeper/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
  end

  def create
    runner = Runner.find_by(email: runner_params[:email])
    if runner & runner.authenticate(runner_params[:password])
      session[:runner_id] = runner.id
      redirect_to '/'
    else
      render :login
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to '/'
  end

  private

  def runner_params
    params.require(:runner).permit(:first_name, :last_name, :captain, :phone_number, :email)
  end

end

my-runners-keeper/app/helpers/application_helper.rb
module ApplicationHelper
end

my-runners-keeper/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyRunnersKeeper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <p class="header-links">
      <% if logged_in? %>
        Hello, <%= current_runner.first_name %>!
      <% else %>
        Hello, visitor!  <%= link_to "Log in", sessions_login_path %> or <%= link_to "Register", runners_new_path %>
      <% end %>
      | <%= link_to "Home", root_path %>
    </p>
  </header>
<%= yield %>

</body>
</html>

my-runners-keeper/app/views/pages/index.html.erb
<div class="index-main">
</h1>Welcome to My Runner's Keeper!</h1>
<p> Here we post our run info and personal contact info to make it easier to encourage each other to run more frequently.</p>

<h3> Click here to see all <%= link_to "runners", runners_path %> </h3>
</div>

my-runners-keeper/app/views/runners/index.html.erb
<h1> Here is a list of all runners in our group </h1>
<% @runners.each do |runner| %>
  <li> <a href="runners/<%= runner.id%>"> <%= runner.full_name %> </a> </li>
<% end %>

my-runners-keeper/app/views/runners/show.html.erb
<div class="runner_show">

  <h3> <%= @runner.full_name %> </h3>
    <ul>
      <% if @runner.captain %>
        <li class = "captain_bullet"> Captain </li>
      <% end %>
        <li> Email: <%= @runner.email %> </li>
        <li> Phone Number: <%= @runner.phone_number %> </li>
        <li id = "prof_page_photo"> <%= image_tag(@runner.img_url) %> </li>
        <% @runs.each do |run| %>
          <li class="run_display"> Run distance: <%= run.distance %> miles </li>
        <% end %>
    </ul>
</div>